/**
 * Codex CLI configuration generator.
 *
 * Codex reads its configuration from `CODEX_HOME` (default `~/.codex`). Two
 * shapes are supported here, matching the two approaches in the spec:
 *
 *  - `provider` (default): declare a dedicated `[model_providers.<id>]` block
 *    with `env_key`, so the API key lives in an environment variable and never
 *    touches the TOML file. Standard and safest.
 *  - `openai`: override the built-in `openai` provider's base URL via the
 *    top-level `openai_base_url` key and write the key into `auth.json`, which
 *    is what `codex login --with-api-key` produces. Fully hands-off.
 *
 * Provider/credential keys (`model_provider`, `model_providers`,
 * `openai_base_url`) only take effect in the *user-level* config
 * (`~/.codex/config.toml`). Codex ignores them in project-level config and
 * prints a warning, so the generated instructions always target CODEX_HOME.
 *
 * These field names have changed between Codex CLI releases. The generator is
 * pure and fully covered by tests so a rename is a one-line, verifiable change.
 */

export type CodexSetupMode = "provider" | "openai";

export interface CodexConfigInput {
  /** Public gateway origin, e.g. `https://gateway.example.com`. No trailing slash. */
  gatewayBaseUrl: string;
  /** The user's internal gateway API key. */
  apiKey: string;
  /** Default model written to config.toml. */
  model: string;
  /** Wire protocol the gateway speaks for this provider block. */
  wireApi: "chat" | "responses";
  /** Provider id used in `[model_providers.<id>]`. */
  providerId?: string;
  /** Human-readable provider name. */
  providerName?: string;
  /** Environment variable holding the key in `provider` mode. */
  envKey?: string;
}

export interface CodexConfigBundle {
  mode: CodexSetupMode;
  /** Directory the files belong in. */
  codexHome: string;
  configToml: string;
  /** Only produced in `openai` mode. */
  authJson: string | null;
  /** Shell line exporting the key; only meaningful in `provider` mode. */
  envExportBash: string | null;
  envExportPowershell: string | null;
  installBash: string;
  installPowershell: string;
}

const DEFAULTS = {
  providerId: "codex_gateway",
  providerName: "Codex Gateway",
  envKey: "CODEX_GATEWAY_API_KEY"
};

/** TOML basic strings escape backslash, quote and control characters. */
export function tomlString(value: string): string {
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  return `"${escaped}"`;
}

/** A TOML bare key stays bare only if it matches `[A-Za-z0-9_-]+`. */
export function tomlKey(value: string): string {
  return /^[A-Za-z0-9_-]+$/.test(value) ? value : tomlString(value);
}

/** Strip any trailing slash so callers can append `/v1` deterministically. */
export function normalizeOrigin(url: string): string {
  return url.trim().replace(/\/+$/, "");
}

/** The OpenAI-compatible base URL Codex should call. */
export function gatewayApiBaseUrl(gatewayBaseUrl: string): string {
  const origin = normalizeOrigin(gatewayBaseUrl);
  return origin.endsWith("/v1") ? origin : `${origin}/v1`;
}

/** Single-quoted POSIX shell literal: safe for any content. */
export function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** PowerShell single-quoted literal: only `'` needs doubling. */
export function powershellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function buildConfigToml(input: Required<CodexConfigInput>, mode: CodexSetupMode): string {
  const baseUrl = gatewayApiBaseUrl(input.gatewayBaseUrl);

  if (mode === "openai") {
    return [
      "# Generated by Codex Gateway — user-level config (~/.codex/config.toml)",
      "# Mode: override the built-in `openai` provider. The API key lives in auth.json.",
      `model = ${tomlString(input.model)}`,
      `model_provider = "openai"`,
      `openai_base_url = ${tomlString(baseUrl)}`,
      ""
    ].join("\n");
  }

  return [
    "# Generated by Codex Gateway — user-level config (~/.codex/config.toml)",
    "# Mode: dedicated provider. The API key stays in an environment variable.",
    `model = ${tomlString(input.model)}`,
    `model_provider = ${tomlString(input.providerId)}`,
    "",
    `[model_providers.${tomlKey(input.providerId)}]`,
    `name = ${tomlString(input.providerName)}`,
    `base_url = ${tomlString(baseUrl)}`,
    `env_key = ${tomlString(input.envKey)}`,
    `wire_api = ${tomlString(input.wireApi)}`,
    ""
  ].join("\n");
}

function buildInstallBash(input: Required<CodexConfigInput>, bundle: {
  configToml: string;
  authJson: string | null;
  envKey: string;
  mode: CodexSetupMode;
}): string {
  const stamp = "$(date +%Y%m%d-%H%M%S)";
  const lines = [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    'CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"',
    'mkdir -p "$CODEX_HOME"',
    `backup() { [ -f "$1" ] && cp "$1" "$1.bak.${stamp}" && echo "Backed up $1"; return 0; }`,
    'backup "$CODEX_HOME/config.toml"',
    ...(bundle.authJson ? ['backup "$CODEX_HOME/auth.json"'] : []),
    `cat > "$CODEX_HOME/config.toml" <<'CGW_CONFIG_EOF'`,
    bundle.configToml.trimEnd(),
    "CGW_CONFIG_EOF"
  ];

  if (bundle.authJson) {
    lines.push(
      `cat > "$CODEX_HOME/auth.json" <<'CGW_AUTH_EOF'`,
      bundle.authJson.trimEnd(),
      "CGW_AUTH_EOF",
      'chmod 600 "$CODEX_HOME/auth.json"'
    );
  } else {
    // Persist the env var in the user's shell profile, and export it for the
    // current shell so `codex` works immediately without reopening a terminal.
    lines.push(
      `PROFILE="$HOME/.zshrc"; [ -n "\${BASH_VERSION:-}" ] && PROFILE="$HOME/.bashrc"`,
      `touch "$PROFILE"`,
      `sed -i.bak "/^export ${input.envKey}=/d" "$PROFILE"`,
      `echo "export ${input.envKey}=${shellSingleQuote(input.apiKey)}" >> "$PROFILE"`,
      `export ${input.envKey}=${shellSingleQuote(input.apiKey)}`,
      `echo "Added ${input.envKey} to $PROFILE"`
    );
  }

  lines.push('chmod 600 "$CODEX_HOME/config.toml"', 'echo "Codex is now pointed at the gateway."');
  return lines.join("\n") + "\n";
}

function buildInstallPowershell(input: Required<CodexConfigInput>, bundle: {
  configToml: string;
  authJson: string | null;
  mode: CodexSetupMode;
}): string {
  const lines = [
    "$ErrorActionPreference = 'Stop'",
    "$codexHome = if ($env:CODEX_HOME) { $env:CODEX_HOME } else { Join-Path $HOME '.codex' }",
    "New-Item -ItemType Directory -Force -Path $codexHome | Out-Null",
    "$stamp = Get-Date -Format 'yyyyMMdd-HHmmss'",
    "function Backup-CgwFile($path) { if (Test-Path $path) { Copy-Item $path \"$path.bak.$stamp\"; Write-Host \"Backed up $path\" } }",
    "Backup-CgwFile (Join-Path $codexHome 'config.toml')",
    ...(bundle.authJson ? ["Backup-CgwFile (Join-Path $codexHome 'auth.json')"] : []),
    "$config = @'",
    bundle.configToml.trimEnd(),
    "'@",
    "Set-Content -Path (Join-Path $codexHome 'config.toml') -Value $config -Encoding utf8 -NoNewline"
  ];

  if (bundle.authJson) {
    lines.push(
      "$auth = @'",
      bundle.authJson.trimEnd(),
      "'@",
      "Set-Content -Path (Join-Path $codexHome 'auth.json') -Value $auth -Encoding utf8 -NoNewline"
    );
  } else {
    lines.push(
      `[Environment]::SetEnvironmentVariable(${powershellSingleQuote(input.envKey)}, ${powershellSingleQuote(input.apiKey)}, 'User')`,
      `$env:${input.envKey} = ${powershellSingleQuote(input.apiKey)}`,
      `Write-Host "Set ${input.envKey} for the current user."`
    );
  }

  lines.push("Write-Host 'Codex is now pointed at the gateway.'");
  return lines.join("\n") + "\n";
}

export function buildCodexConfig(
  raw: CodexConfigInput,
  mode: CodexSetupMode = "provider"
): CodexConfigBundle {
  const input: Required<CodexConfigInput> = {
    ...DEFAULTS,
    ...raw,
    gatewayBaseUrl: normalizeOrigin(raw.gatewayBaseUrl),
    providerId: raw.providerId ?? DEFAULTS.providerId,
    providerName: raw.providerName ?? DEFAULTS.providerName,
    envKey: raw.envKey ?? DEFAULTS.envKey
  };

  const configToml = buildConfigToml(input, mode);
  const authJson =
    mode === "openai"
      ? JSON.stringify({ OPENAI_API_KEY: input.apiKey }, null, 2) + "\n"
      : null;

  return {
    mode,
    codexHome: "~/.codex",
    configToml,
    authJson,
    envExportBash: mode === "provider" ? `export ${input.envKey}=${shellSingleQuote(input.apiKey)}` : null,
    envExportPowershell:
      mode === "provider"
        ? `$env:${input.envKey} = ${powershellSingleQuote(input.apiKey)}`
        : null,
    installBash: buildInstallBash(input, { configToml, authJson, envKey: input.envKey, mode }),
    installPowershell: buildInstallPowershell(input, { configToml, authJson, mode })
  };
}

/** Numbered manual steps rendered next to the one-line installer in the UI. */
export function codexManualSteps(bundle: CodexConfigBundle, envKey: string): Array<{
  title: string;
  body: string;
  language: "bash" | "toml" | "json";
}> {
  const steps: Array<{ title: string; body: string; language: "bash" | "toml" | "json" }> = [
    {
      title: "Create the Codex home directory",
      body: 'mkdir -p "${CODEX_HOME:-$HOME/.codex}"',
      language: "bash"
    },
    {
      title: "Write ~/.codex/config.toml",
      body: bundle.configToml.trimEnd(),
      language: "toml"
    }
  ];

  if (bundle.authJson) {
    steps.push({
      title: "Write ~/.codex/auth.json",
      body: bundle.authJson.trimEnd(),
      language: "json"
    });
  } else {
    steps.push({
      title: `Export ${envKey} in your shell profile`,
      body: bundle.envExportBash ?? "",
      language: "bash"
    });
  }

  steps.push({ title: "Verify the connection", body: "codex --version && codex", language: "bash" });
  return steps;
}
